### ISSUE TITLE
First set of performance plots for 2023

### ISSUE THREAD

**Issue by sroychow** [CMSTrackerDPG/Tasks#16]
Title says it all. Here are a few items. Conveners are encouraged to add more.

Pixels

- [x] Bias scans
- [ ] Timing scan 
- [x] Cluster charge
- [x] Cluster size X-Y
- [x] Hit efficiency
- [x] Hit residuals
- [x] Trend of cluster charge
- [ ] Good detector fraction trends
- [x] Lorentz Angle

Strips

- [x] Bad component trend
- [ ] S/N 
- [ ] Hit efficiency
- [ ] Hit residuals (??)

Alignment

- [ ] DMR
- [ ] PV validation plots
- [ ] Trends of DMRs

Common to all :-
- Each note should contain an abstract and it should mention the amount of lumi used.
- Also adding a conclusion slide may be nice

**Latest approvals from RC can be on 30/06/2023** so that it can be shown in conference starting from July 2nd week.

**Comment by consuegs** [comment]
Hi @sroychow, all, you can find the plans from the Tracker Alignment group below.

**Dates:**
**Pre-approval:** 28.06 (if ready one week before we will notify in advance to move the presentation to previous Tracker DPG meeting on 21.06)
**Approval:** 30.06
**Twiki page (in construction):** https://twiki.cern.ch/twiki/bin/view/CMSPublic/TkAlignmentPerformance23
**People:** Sandra, Daina, Lakshmi

In terms of results we plan to prepare two sets of plots

1. CRAFT alignment / 2022 geometry performance with Cosmics Commissioning data
2. CRAFT / 900 GeV / 13.6 TeV geometries performance on 13.6 TeV data

Concerning trends, given that we do not have multi-IOV offline object the plan is to leave this for the second note of the year since we would have only one curve to show now.
